# Generated by Django 4.1.2 on 2022-11-22 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0004_wishlist"),
    ]

    operations = [
        migrations.CreateModel(
            name="Checkout",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("total", models.IntegerField()),
                ("shipping", models.IntegerField()),
                ("final", models.IntegerField()),
                (
                    "rppid",
                    models.CharField(blank=True, default="", max_length=30, null=True),
                ),
                ("date", models.DateTimeField(auto_now=True)),
                (
                    "paymentmode",
                    models.IntegerField(
                        choices=[(0, "COD"), (1, "Net Banking")], default=True
                    ),
                ),
                (
                    "paymentstatus",
                    models.IntegerField(
                        choices=[(0, "Pending"), (1, "Done")], default=True
                    ),
                ),
                (
                    "orderstatus",
                    models.IntegerField(
                        choices=[
                            (0, "Order Placed"),
                            (1, "Not Packed"),
                            (2, "Packed"),
                            (3, "Ready to Ship"),
                            (4, "Shipped"),
                            (5, "Out for Delivery"),
                            (6, "Delivery"),
                            (7, "Cancelled"),
                        ],
                        default=True,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="mainApp.buyer"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CheckoutProducts",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "checkout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.checkout",
                    ),
                ),
                (
                    "p",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mainApp.product",
                    ),
                ),
            ],
        ),
    ]
