# Generated by Django 4.1.2 on 2022-12-03 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0005_checkout_checkoutproducts"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkoutproducts",
            name="qty",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="checkoutproducts",
            name="total",
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
