# Generated by Django 4.1.2 on 2022-12-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0006_checkoutproducts_qty_checkoutproducts_total"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=30)),
                ("email", models.EmailField(max_length=30)),
                ("phone", models.CharField(max_length=15)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "active"), (1, "Done")], default=0
                    ),
                ),
                ("date", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
