# Generated by Django 4.1.2 on 2022-12-04 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mainApp", "0007_contact"),
    ]

    operations = [
        migrations.AddField(
            model_name="buyer", name="otp", field=models.IntegerField(default=-1734755),
        ),
    ]
